== Selection from the Life of William Lewis

[.centered]
=== A Letter of William Lewis

[.salutation]
My Dear Friend,

When I consider the depth and strength of self-love in the fallen soul of man,
broken off from union with the perfect will of its glorious Creator;
and the almost perpetual springing forth of proud desires,
branching and spreading in some direction or other from this bitter root;
writing or even speaking of ourselves appears to my view to be
an engagement requiring great watchfulness and self-abasement.
Under this persuasion I have cautiously avoided written
correspondence regarding my own spiritual concerns,
and have long believed it would be better for all spiritually minded persons (particularly
those who are young) to be less employed in this way than is commonly the case;
for I apprehend that many are not sufficiently aware of the subtle workings of him, who,
in a disguised appearance, can secretly awaken desires after personal significance,
and a strong interest for ourselves in the minds of our friends,
desiring them to consider us as people of great religious experience,
though we may (with words) profess feelings of weakness and class
ourselves with the lowest rank in the school of Christ.

Such being my sentiments,
it will not appear strange to you that I have been slow in complying with your
request to give you some account of my spiritual experiences and movements.
At last, however, I take up my pen for that purpose,
and as the engagement will necessarily involve recollections of a very humiliating kind,
I hope it will serve as a defense against the dangers already alluded to.

I was born the 17th of the 9th Month, 1753.
There was nothing very remarkable attached to my early days that I can now recollect.
I say nothing very remarkable because, unhappily, an early desire for,
and a pursuit after all that is in the world is (in a greater
or lesser degree) the course of every natural man`'s heart,
according to his own particular temperament or bias.
My own, I remember, was strongly drawn out after lying vanities,
the participation in which was limited only by my meager resources and
by parental authority that imposed upon me a close confinement to business,
into which I was introduced in my fourteenth year.
I possessed little from my previous education besides a knowledge of writing and arithmetic,
which was all that my father judged necessary for
a plain mechanic (his designation respecting me).

Previous to this period,
the only effect of the in-shining of divine Light in my dark heart (that I now
remember) was the solemn and impressive authority of the Holy Scriptures,
and the beauty that appeared to my view in a true holiness of life,
and an entire dedication of heart unto Almighty God.
This led me greatly to admire,
and even to take some comfort in considering His ancient servants,
whose lives were fully devoted to Him;
and also to regret the falling short of some others
who appeared to have a degree of zeal for His glory.
But at the age of fourteen, the convicting power of the precious light was sensibly felt,
and condemnation was awfully witnessed in my pursuit of sinful pleasures--none
of which were ever indulged in without feeling a dread of that eye,
from which I both knew and felt that nothing could be hidden.
To lessen this terror, I formed some weak resolutions to resist when next I was tempted,
but these determinations being chiefly the effect of fear,
and resorted to only to cool the fiery indignation I felt burning in my conscience,
were generally broken in the hour of trial.
Such feelings continued for a considerable time,
and a faint hope was sometimes cherished of one day emerging
from the miry clay into which I had plunged my poor soul;
but no real effort was made to break off from my evil ways.

My free time was mostly spent in reading plays and novels,
and hereby a lazy and weak frame of mind was excited and nourished.
I grew exceedingly fond of dress,
and indulged more and more in anything that gratified such a spirit.
Useful and instructive books appeared dry and tasteless; business,
and almost anything that required mental energy and steady attention,
became heavy and irksome.
Thus, even the desire to struggle for deliverance, seemed in great measure to disappear.
And though a dread of the consequences of continuing
in such a course would at times awaken in me,
yet I thought it next to an impossibility for anything
to loosen my affections from the world.
For my poor mind was so tenacious after present enjoyment,
and so fearful of any interruption thereof, that I well remember the alarm I felt,
lest the doctrine preached by the clergyman of the parish in which I resided,
at the time called Christmas, should at all convict or hinder our merriment.
For we heard it preached that this holiday time was set apart by
the Church for the purpose of piously commemorating the mercy and
love of our heavenly Father in sending His dear Son into the world,
in order that, by delivering us from its corruptions,
our spirits might be fitted and prepared for an abode
with Him in the realms of light and purity.
Now, I knew that if this doctrine were truly believed
and acted upon by the elderly part of the auditors,
our merry meetings (which were my chief joy at this season) would necessarily be discontinued;
for,
even in this dark state (without recurring to any doctrine or precept) I felt
an inward conviction of the incompatibility of a desire after worldly delights,
with true spiritual hunger; and indeed,
supposing that both can subsist together in the same
heart involves an incongruity of the greatest magnitude.
A refuge, however, from these fears was near at hand.
For I then recollected that the same doctrine had been preached, heard,
and admired many times before;
but this had always ended in both preacher and hearers going away
and continuing to throw in their mite for the promotion of feasting,
dancing, singing, and mirth.
Thus my alarm was quieted, in the hope that things would continue in their usual course,
and that we should continue to "`chant to the sound of stringed instruments,
drink wine out of bowls, and anoint ourselves with the best ointments,`"^
footnote:[Amos 6:5]
undisturbed by any apprehensions of future woe for our present ease; or at least enabled,
by the comfort derived from joining hand in hand,
to silence these concerns to a tolerable degree.

Such was my condition at this early period of my life.
It continued,
without any significant alteration until the year 1775 (the 22nd of my life),
when I was powerfully wrought upon by the Spirit of Truth,
and suddenly formed an earnest purpose of heart to break off from my sins,
and to seek peace with my God in a truly religious course of life.
Immediately upon making this resolution, I acted upon it.
I threw off my gaudy apparel,
and restricted myself to careful moderation in satisfying the real needs of nature--cutting
off everything that seemed like unnecessary indulgence in eating,
drinking, sleeping, etc., in a word, all that was done for mere recreation.
I then strictly endeavored to redeem whatever precious
time I could spare when released from outward business,
by retiring into my bedroom, or attending a public place of worship.
In private, I prayed frequently, earnestly, and at as much length as I could,
knowing at this time very little of such christian practices.
Being quite uninformed respecting doctrines,
I had no predisposition towards any particular sect on account
of their distinguishing tenets or forms of public worship;
but having long entertained a high opinion of the
Wesleyan Methodists from their daily meeting together,
I frequented their assemblies for a time.
After this,
at the persuasion of a friend professing among another
other sect (i.e. the followers of George Whitfield),
I became a hearer at the Tabernacle, and hastily joined in membership there.
I call it hastily, because there was no previous examination of their opinions,
nor any earnest seeking to the Fountain of wisdom for direction.
As much as I remember of my feelings at that time,
they were so strongly excited by the main object of my new course--namely,
peace with God,
and a well grounded hope of being admitted to His heavenly kingdom at last--that
very little room was left in my mind to be concerned about points of doctrine.
Such a sweetness, for a time, accompanied my religious exercises,
that it seemed enough for me to hear of God`'s mercy in Christ Jesus,
and that an experiential participation therein was attainable in this present world.
And these things being set forth in a lively manner by those preachers,
were so much like marrow and fatness to my soul,
that other points of doctrine which were occasionally introduced,
made but little impression upon me, and consequently obtained very slight consideration.
But this state of mind, little by little,
was disturbed on my being questioned as to the ground of
my selecting this body of believers from among the rest,
and upon what foundation.

I then began to build my religious doctrinal opinions,
which naturally coincided with those of my brethren at the Tabernacle,
and so became tenacious in that respect.
A sectarian spirit soon found entrance,
and under its influence I began to search the Scriptures with a view to collect all
they contained that would bear an interpretation favorable to the Calvinist system;
laboring hard against the force of many scriptural passages
which I found impossible to reconcile with that system,
and struggling with an inward conviction (regardless how hard I tried
to dismiss it) which opposed a belief in the partiality of God,
and in a covenant of grace in Christ Jesus which
extended to only a few of His fallen creatures,
leaving the rest to perish eternally.

Being thus exercised,
the good providence of my heavenly Father directed the attention
of a piously disposed neighbor to my state;
who (much concerned at the danger I appeared to be in of imbibing the
doctrines alluded to) put into my hand some deeply spiritual writings,
by which my mind was clearly and fully convinced of my error.
I soon desisted from my adherence to a doctrine which nothing
but sectarian determination had introduced me into;
and I saw clearly that in order to maintain it, I had resisted my own convictions,
rejected the plain doctrines and declarations of prophets, apostles,
and Christ Jesus Himself,
and almost totally abandoned every thought of Almighty God that
was reconcilable with a belief in His goodness and justice.
Oh, what a shocking idea that a good and gracious God would permit
myriads upon myriads of intelligent spirits to come into existence,
with nothing before them but a wearisome painful passage through a valley of tears,
abounding with trouble and sorrow,
only to terminate by their entrance into a state still more replete with suffering,
where inconceivable woe, horror, and anguish must be their portion to all eternity!
How monstrous to believe that _any_ of God`'s creatures should have,
by His irrevocable appointment, such a destination!
How unworthy a thought of God to suppose that,
with the secret purpose of condemning the majority of mankind,
He would yet commission prophets and apostles to
call them to a participation in His glorious nature,
to seek an inheritance in His blessed kingdom,
and at length even send His dear Son among them to
invite souls more fervently to unspeakable joy;
declaring in the plainest terms that any incapacity for receiving
His offer is due entirely to a willful indisposition of heart,
saying: "`You will not come unto Me that you might have life.`"^
footnote:[John]

But to return to my particular state.
Released from these shackles,
my mind found sweet liberty in acknowledging the universal
offer of God`'s love in Christ to His creature man;
in receiving the apostolic testimony of His being "`no respecter of persons;`"^
footnote:[Acts 10:34]
and rejecting every opinion and doctrine that was not built on this foundation.
The Holy Scriptures were now perused with openness of heart,
and laying aside all preconceived opinions, I was soon convinced of the following truths:

[.numbered-group]
====

[.numbered]
1+++.+++ That the work of religion is wholly inward,
and wrought by the operation of God`'s Holy Spirit.

[.numbered]
2+++.+++ That true worship is also inward,
consisting principally in a humble prostration of spirit before the omnipresent Creator,
who is the "`God of the spirits of all flesh;`"^
footnote:[Numbers 16:22,27:16]
"`a God near at hand, and not afar off,`"^
footnote:[Jeremiah 23:23]
"`in whom we live, and move, and have our being.`"^
footnote:[Acts 17:28]

[.numbered]
3+++.+++ That the Almighty God, in the riches of His mercy,
has sown into the heart of every man a gift or measure of His living Word;
a real seed of His heavenly divine nature.^
footnote:[Which can be resisted and rejected,
or "`received with meekness`" unto the saving of the soul.
See James 1:21; Matthew 13:3-9; John 1:9; Romans 1:19.]

[.numbered]
4+++.+++ That the arising of this "`incorruptible seed`" into a predominant power of life
in the soul of man is as necessary for the true perception of spiritual things,
as a participation in the human nature is necessary
for the knowledge of the things of a man.
The quickening operation of the Holy Spirit in and upon this unspeakable
gift is what gives the soul a renewed sensibility of God`'s holy presence,
and is essential for acts of true worship.
This ought therefore to be reverently sought after and waited for,
"`in the hope that they might find Him, though He is not far from each one of us.`"^
footnote:[Acts 17:27]

[.numbered]
5+++.+++ That consequently, the faith to which all things are possible,
is something of a much deeper nature than a mere
assent of the judgment to truths or doctrines,
or an agreement with what is called by many,
the "`Gospel Plan of Salvation,`" or even with what
is contained in the whole creed of systematic divinity.

====

The spiritual writings before alluded to were undoubtedly used
of the Lord to bring greater clarity in these new convictions;
but the seal that fully stamped them in my heart was the apostle`'s testimony at Athens,
where he sets forth the creature`'s true relation to his glorious Creator,
the high origin and destination of man,
and his consequent proper exercise and glorious privilege, namely:
"`that they should seek the Lord, in the hope that they might grope for Him and find Him,
though He is not far from each one of us;
for in Him we live and move and have our being.`"
Oh, that expression, "`That they might grope for him!`"
How forcibly does it impress the necessity of a deep introversion of spirit,
in seeking access to the Fountain of purity and love.

With this view of things, and under these impressions, the manner of worship,
as well as the verbal communications at the Tabernacle soon became unsatisfactory to me.
I then began to think of, and finally resorted to,
the meetings of the Society of Friends,
chiefly on the ground of their gatherings being conducted in a way that was more compatible
with my convictions than those of any other religious society that I had knowledge of;
though I did also have some expectations from the ministry among them,
believing that those who were really called to the work could directly
receive what was suitable to the states of those to whom they ministered.
The vocal communications I heard among Friends were direct, convincing,
and very clear upon many points about which I had been troubled.
At times they were deeply spiritual, enforced with power,
and accompanied with something which conveyed to
my feelings that they were the result of living experience.
All of this tended to deepen my recent impressions,
and I began to act in correspondence with them.
In my hours of retirement, instead of singing, uttering long lists of petitions,
and reading, I began to wait in silence,
with earnest desires after inward solemnity and prostration
of spirit before the Holy One,
longing after that quickening power which contrites and
prepares the heart to receive divine communications,
and upon receiving them, returns all to the great Giver of every perfect gift.

Ceasing, in this manner, from so much creaturely activity,
and my attention being confined more to what passed within my own breast,
a painful conviction quickly ensued of my being in
reality (with regard to spiritual things) "`wretched,
miserable, poor, blind and naked.`"^
footnote:[Revelation 3:17]
That precious light which had previously visited me with sweet drawings,
now allured me into the wilderness and showed me the "`desert land`" of my own heart;
and it was at this time that the dark workings of unbelief and impatience
began to suggest to me that the Lord had surely abandoned me.
I then began to call into question the little spiritual
experience that I had known prior to this,
and at length considered it mostly the effect of a heated imagination.
Distress and anguish of soul quickly took ground,
and I found myself writing bitter things against myself almost continually.
Then, refusing every hope of comfort, a door was opened for depression; oh,
it entered my very veins, and I soon let go all of my confidence in God.
The bitter cup of despair was tasted; and considering myself forsaken of my God,
I cried and sobbed aloud from disquietude of soul.

As you must assume, I could not continue long in such a condition as this;
relief would naturally be sought for in some way.
The cruel and subtle one was near, and thoughts like these were presented to my mind:
"`I have deceived my soul in imagining myself to be an object of divine mercy,
and in attributing my first feelings and hopes to the operations of grace.
My heart and affections are still earthly and sensual,
though my imagination for a time fondly pictured a more heavenly interior.
I have also deceived my brethren and the world in making a religious profession.
And now, seeing myself in the true light, I must from now on show myself as I really am,
and no longer continue as a wolf in sheep`'s clothing.`"

To a mind weary and comfortless,
in which the seed of life was not sufficiently rooted
so as to enable me to patiently endure tribulation,
this bait of the enemy was unhappily swallowed.
And after some months of deep wading, or rather plunging in dark waters,
in an evil hour I yielded to the suggestion that "`rest was good`"^
footnote:[Genesis 49:15]
no matter how it was obtained.
The land of my heart which I had before viewed as
a howling wilderness and a valley of tears,
now seemed more pleasant and easy,
and so I again bowed my neck to the yoke of sin and became a slave of forced labor.
Religious restraint was then in great measure thrown aside,
although for a time I kept within the bounds of morality,
and maintained such order as was common in my father`'s house,
going with my family on the first day of the week to their place of worship,
called the church, and hearing some of them read the Scriptures.
But alas,
these bounds soon became painfully narrow to my selfish
will and the workings of my natural propensities.
And when I departed from the one restraining power,
they awoke with strength in my enslaved heart and gradually took the reins,
so that I was indeed led captive at the will of the cruel tempter of mankind.
In time, no desire to resist temptation remained in me,
but every new path that opened anything pleasant to my view was eagerly pursued.
I resorted to taverns,
and gaming (the chief pleasure there) became peculiarly attractive,
so that whole nights were devoted to this destructive vice.
In short, sad as it is to relate, I became a complete libertine,
and my last state was now much worse than my first.

Before I proceed further in reciting the consequences of my vile apostasy,
it may be best, in order to give a clear view of what really took place,
to go back a little to the gloomy state and exercises which preceded it.
As I have already said, my first resolution to devote myself to Almighty God was sincere.
I really intended, from that day forward, to look singly unto Him for my portion.
But my vows were made hastily,
without counting (and indeed without knowing) the cost of discipleship.
I was also in a state of considerable ignorance concerning myself,
particularly with regard to my instability of spirit,
my fearfulness of mind which shrunk away from suffering,
and my tenacity in the pursuit of present enjoyments, whatever object was in view.
Humility,
the main requisite for laying a sure foundation for stability and real spiritual advancement,
was but little regarded.
Great things were desired and expected from the outset,
and human emotion was cherished as a mark of true zeal,
and mistakenly thought to be a feature of the renewed and pure image.

When, therefore, I was led to look inward,
and became more intimately acquainted with myself;
when I came to some discernment with regard to the
difference between creaturely heat and divine light;
and when I was made to feel the convicting power of the latter,
and see therein my condition to be so far below what I had thought it to be;
then there was great distress that arose from the fleshly part,
which gradually gaining ground, gave the enemy an advantage,
and at length a triumph over me.
Self-love having nothing to feed upon, soon became weary of privation,
and was burdened under such a humiliating fast.
Retirement for private devotions,
having been divested of all that had at first given it a sweet relish,
became irksome to me, and excuses for omitting it were easily allowed, if not sought for.
One, I very well remember; namely,
I began to converse upon religious subjects during the times
which I had formerly allotted to private devotion.
But conviction soon followed,
and I saw that I resorted to this as a relief from
the weight of my own proper exercise and burden.
This brought condemnation and an increase of discouragement,
and my confidence naturally diminished.
Acts of rebellion against clear conviction in other things soon followed, until,
at length, I entirely let go of my hope.
The heavens were as brass over my head,
and having no expectation of any prayer of mine being able to pass through,
it ultimately produced the effects already alluded to.
Thus you see, my friend, there was a "`drawing back`"^
footnote:[Hebrews 10:38-39]
in the hour of tribulation, instead of "`keeping the word of patience.`"^
footnote:[Revelation 3:10 KJV]
Divine love had indeed allured me, and brought me into the wilderness,
into the valley of Achor (i. e. trouble),
which in His wisdom was the allotted place for me to dwell for a time.
If I had continued there until all that hindered my progress towards victory
over my soul`'s enemies had died their appointed death--hoping and quietly waiting
for the Lord`'s salvation--I doubtless would have been given vineyards from there^
footnote:[Hosea 2:14-15]
and sung of the Lord`'s salvation,
which He can surely give to the truly humble and poor in spirit,
even in the night season.

But, sorrowful to relate!
I now became a slave to my own natural propensities.
Unable to bear personal reflection, company was eagerly and continually sought after,
and every means was used to silence the voice of conscience,
which was still awfully loud at times.
For although I thus sought to flee from the presence of the Lord of heaven and earth,
yet such was His pity and mercy to my poor soul, that He forsook me not utterly.
In the secret of my heart, I was still pierced with the arrows of His convicting light,
and pressed sore with a horrible dread of death and judgment to come.
Nevertheless, for the space of twelve years,
relief was sought only by immersing myself deeper and deeper into libertine pursuits;
so that I courted even those vices to which I had no particular leaning;
and (if there is such a thing) I tempted the tempter,
and indeed became his "`lawful captive.`"^
footnote:[Isaiah 49:24]
Oh, is there any condition more replete with internal horror
and gloom than that of such a backslider?

In the course of this long night of apostasy, some significant events took place.
I married, and had several children.
I also formed a promising connection in trade,
in which there was a fair prospect of providing for my family.
But, not being sufficiently alive to the weight of the
solemn obligations that I was now under,
pleasure was generally pursued with eagerness, particularly gaming;
and business and family duties becoming increasingly insipid, were greatly neglected.

Thus I went on, apparently carefree and happy, but in reality miserable,
until the year 1789, the thirty-sixth year of my age,
when it pleased my long-suffering and merciful God to visit me with severe illness.
Wholly confined by this,
I was now left to my own thoughts and reflections on my past course,
and made to awfully feel the state it had brought me to; that is,
to be "`without hope and without God in the world.`"^
footnote:[Ephesians 2:12]
"`Destruction and misery (I knew) were in my paths,`"^
footnote:[Romans 3:16]
and I was soon convinced that there was no hope of finding the path of peace except
by turning with full purpose of heart unto Him from whom I had so deeply revolted.
A partial reformation I knew was odious in the sight of my omniscient Creator,
especially for such a one as myself.
My former views concerning a truly religious condition,
and the deep inward work that was necessary to pass through in order to attain it,
all returned.
I saw the cost of real discipleship with a crucified Master,
and the sight was terrifying to my long-corrupted and debased spirit.
The "`world`'s dreaded laugh`" was also no small thing to take into account;
for by this time, I was known to many of various classes in civil society,
and through marriage connections I was intimate with
some who lived in much grandeur in manners and estates.
To all of this was added a strong apprehension that
my natural instability would ever be prevalent,
and that I would never attain to a faithfulness of spirit.
The struggle was deep and painful, but at length,
strength was granted to renew my covenant with a good and
gracious God who had long waited for my return,
and who now loudly called me to exalt Him in such a way as would make me capable of
a participation in His living mercies and tender forgiveness of my manifold sins.

Accordingly, on the 26th day of the 9th month, 1789,
in the sight of a heart-searching God, I took up a resolution, from that time,
to earnestly seek for peace with Him; to break off from all my evil habits,
and enter upon a truly religious course,
earnestly praying for strength to perform my vows,
and dreading nothing as much as unfaithfulness,
or an abatement of the fervent desires which I then
felt to return to my heavenly Father`'s house.
The Lord graciously regarded my petitions.
He delivered me from that horror at the thought of
death which had long been deeply felt in my soul.
Thus I gathered a little strength, and my head was lifted up, at times, in hope.
And in the beginning of the year 1790,
I was also favored with a return of bodily strength,
so that matters both inward and outward, appeared more cheerful than for many years past.
But oh, I little imagined what a cloud was gathering,
and was about to overwhelm me in the deepest gloom!

[.asterism]
'''

+++[+++Our dear friend here enters into particular details which cannot, with propriety,
be thrown before the public.
Suffice to say, that the gathering cloud burst heavily upon him.
His domestic comforts were broken up by several very afflictive circumstances;
added to which, (by the sudden decease of his father about the same time,
and some very unexpected consequences ensuing) his
concerns in trade were so seriously affected,
that although he continued for several years,
he ultimately found it necessary to relinquish his business entirely,
with the loss of nearly all of his property,
and to resort to the employment of an accountant for his subsistence.
But, those who knew him at this period can bear testimony to
his christian demeanor under these deeply trying events.
And there is good ground to believe that, by his patience and resignation under them,
they became a blessing to him.]

[.asterism]
'''

In what thus outwardly befell me, I think it was verified,
that sooner or later the backslider in heart is made to eat the fruit of his own ways,
and that many stripes are prepared for those who, knowing their Master`'s will,
rebel against it.^
footnote:[Luke 12:47]
I now come to the relation of the exercises and convictions which led
to my joining the people with whom I am now in religious fellowship.

My convictions concerning religion and the worship of Almighty
God continued the same as they were in my earlier days,
and consequently the principles and practices of every society
of christians were quite different from my sentiments,
except for those of Friends.
Yet believing the division of the church into sects to be
the consequence of a departure from the pure Spirit of Christ,
I strongly questioned for a time the propriety of my joining any one of them exclusively;
and so I determined to seek God in secret for His guidance in this matter,
occasionally attending the different assemblies,
but mostly those of the Friends and Methodists.
To many, this conduct likely appeared to be the effect of an unsettled judgment;
but that was not exactly the case.
For I stood upon the ground before-mentioned,
still believing in the necessity of the holy quickening power of God to
revive in man the lost holy image in which he was first created,
and that Jesus Christ was this power, inwardly revealed in man.
Consequently,
looking to anything short of this for help seemed to me to be clinging
to something founded on that covenant which "`made nothing perfect,`"^
footnote:[Hebrews 9:9]
because it stood in exterior observations which could
do nothing effectual as pertaining to the conscience.
The baptism, therefore, that truly saves,
was (in my view) such a union with the world-renouncing Spirit of Jesus
Christ as gives the victory over sin and the world in the present time;
thus the apostle says, "`As many as were baptized into Christ have put on Christ.`"^
footnote:[Galatians 3:27]
"`They that are Christ`'s have crucified the flesh with its affections and lusts, etc.`"^
footnote:[Galatians 5:24]
This I took to be the true spiritual baptism.

The supper of the Lord (so called) which Christ Himself enjoined,
was certainly an eating of "`His body`" and a "`drinking of His blood,`"^
footnote:[John 6:53]
(for as Paul says elsewhere, "`there is a spiritual body`"^
footnote:[1 Corinthians 15:44]). But here again,
all exterior acts appear very insignificant,
seeing that Christ declared this participation of His flesh and blood to be a
union with Him of the same nature as His union with His heavenly Father:
"`He who eats My flesh and drinks My blood abides in Me, and I in him.
As the living Father sent Me, and I live because of the Father,
so he who feeds on Me will live because of Me.`"^
footnote:[John 6:56-57]
Now, if this living union is the thing signified, can we then suppose that,
when partaking of the Passover with His apostles,
Christ intended to appoint the observance of some new outward and visible sign,
instead of this?
Would He, as a High Priest made "`according to the power of an endless life,`"^
footnote:[Hebrews 7:16]
minister to His church in the same way that priests did under the law,
whose gifts and sacrifices, we read,
"`could not make those who performed the service perfect,
because they stood only in foods and drinks and various washings,
and fleshly ordinances imposed upon them until the time of reformation?`"^
footnote:[Hebrews 9:10]
According to Luke, Christ`'s words indeed were, "`This do,
in remembrance of Me;`" but neither Matthew nor John, who were present,
take any notice of this injunction.
Could they possibly have omitted the mention of it if they had considered
it a binding law upon the church according to its literal meaning,
or a new institution established by the Lord himself
to be observed as solemnly as the Passover had been?
I cannot think this to be at all likely.
It seems rather that the injunction, as well as the declaration, "`This is my body,
etc.`" was intended to convey something more spiritual
in its nature than a mere outward act,
which any unregenerate man might perform;
even that to which the apostle Paul alluded when he said,
"`Therefore purge out the old leaven, that you may be a new lump,
since you truly are unleavened.
For indeed Christ, our Passover, was sacrificed for us.
Therefore let us keep the feast, not with old leaven,
nor with the leaven of malice and wickedness,
but with the unleavened bread of sincerity and truth.`"^
footnote:[1 Corinthians 5:7-8]

Now, that the first converts held their "`love feasts`"^
footnote:[Jude 1:12]
in commemoration of our Lord`'s breaking outward bread (in which they
had the sanction of the Apostles themselves) is undoubtedly true.
But may we not reasonably conclude that in this,
as well as in many other outward observances,
they conceded to the weak state of their brethren,
and their strong attachment to Mosaic rites?
That they did so in some particulars (like circumcision), is very evident.
And as to the remarks of the apostle Paul to the Church at Corinth,
concerning the abuses that had prevailed in the manner of keeping those feasts of charity,
nothing in this passage seems to indicate a permanently abiding institution,
nor do the apostle`'s words seem to be directed to a very mature state in the
spiritual life--for he says he "`could not speak unto them as unto spiritual,
but as unto carnal, even as unto babes in Christ.`"^
footnote:[1 Corinthians 3:1]

Concerning some of the other cardinal points in which the Society
of Friends differs from most other bodies of christians--namely,
those of war, swearing,
and the nature of true gospel ministry--I had occasion of publicly
manifesting my unity with these things long before I became a member,
or ever knew that I would be.
Plainness and simplicity in apparel, manners, and speech appeared to me,
from my earliest convictions,
to be quite in line with the precepts and example of our Holy Redeemer;
and I well knew that the vanity of my own heart was
what induced conformity to the world in these respects.
The practice of self-denial in these things, therefore,
appeared appropriate and necessary.
And here it comes to mind to say something about the wide
departure from the simplicity which is in Christ,
and from the guidance of His meek, loving, Holy Spirit,
which is at present so glaring in the outward and visible church; so that in general,
a total disregard both of the letter and spirit of the Gospel of Christ is,
with respect to these points, both allowed and even defended.

Attention to our manner of dress,
as being in any way relevant to our conduct before Almighty God,
or to our walking before Him in humility, righteousness, and holiness,
is ridiculed by many.
Nevertheless,
it is a subject which one of the holy prophets tied
to Israel`'s deep revolt against their Creator,
declaring the impending judgments of God on this account,
(see Isaiah 3:18-24). Another, among wisdom`'s children in the days of old,
declares that "`a man`'s attire, gait, and excessive laughter show what he is.`"^
footnote:[Ecclesiasticus 19:30]
And if we add to this, the plain and positive injunctions of the apostles Paul and Peter,^
footnote:[1 Peter 3:3; 1 Timothy 2:9]
which as expressly forbid attention to the adorning of the person in what is worn,
as the eighth commandment prohibits increasing wealth by fraud in anything that is done,
must we not plainly see that a follower of Christ is called upon to bear,
by their example, a full testimony against conformity to the spirit of the world?
And is it not apparent that the spirit of this world pursues, through fashionable dress,
a significance and honor in appearance that goes
far beyond what our bodily necessities require?

Respecting plainness of speech, I have told you that, to a certain extent,
the propriety of this was in agreement with my previous judgment.
So it was,
but some time elapsed before I felt it necessary to adopt it so fully as Friends do.^
footnote:[Here William Lewis speaks specifically of the manner in which
the English language was being corrupted at that time by addressing individual
persons with plural pronouns in order to show partiality or flattery.
The principle, however,
of honoring the Lord with "`every word that proceeds out of our mouth`" (Ephesians 4:29;
James 3:2-12) is a timeless one,
and the Spirit of Truth will make application in the hearts
of every true disciple regardless of language and culture.]
What led me to a close and deep consideration concerning the ground on
which they believe it right to differ from others in this respect was,
to the best of my recollection, nearly as follows.
After two years of seclusion from all public places of worship
(except when I was particularly invited to any),
in my hours of private retirement, which were then many and daily,
it forcibly came to my view that a course so solitary or reclusive
was not in accordance with either the spirit of the gospel,
the plain injunctions of the apostles,
or the practice of believers in any age of the church.
I saw that brotherly union and fellowship were the very essence of the gospel spirit,
which breathes goodwill to all, loves without dissimulation,
naturally cares for the spiritual welfare of others, and bears their burdens.
Opening my mind more to these considerations, they soon pressed weightily upon me,
and my thoughts turned with desires after religious fellowship.
At my first glance that way,
the Society of Friends appeared to be the only one to whom I could possibly join myself;
but it seemed appropriate that my judgment and practice
should first be altogether in agreement with theirs;
and with the exception of language, they were already nearly so.
But the very idea of a change in this particular caused such a shrinking back,
and such a sense of dread,
as induced an attempt on my part to sift their arguments and prove them groundless.
How far I tried to evade the force of what they advanced
on this subject I do not now recall;
only that ultimately,
a diligent search in the Scriptures concerning this matter was exclusively resorted to.

From about this period (1793),
I began to have a fixed apprehension that I would fall short of divine
requiring if the cross were not submitted to in respect to my language.
Nevertheless, I continued shrinking back and struggling for nearly two years,
during which time many prayers (with tears) were offered
up to a gracious God for guidance in the matter,
and for strength to bear all He might see fit to
lay upon me for the reduction of my natural will,
and the humiliation of my soul before Him.
At length, in much trepidation of spirit,
I submitted to adopt what Friends call "`the plain language,`" whereby,
another stumbling-block was removed out of my path.

From this time onwards (the year 1795) I attended their meetings regularly,
and about three years afterwards, on applying to be admitted as a member of the Society,
I was received as such by the monthly meeting of my native city.

[.signed-section-signature]
William Lewis

[.asterism]
'''

The foregoing narrative of the life and religious experience of William Lewis was written
by himself in the year 1797 in compliance with the earnest request of a close friend.
It was given to this individual with the strict injunction that it should not
be published or even copied for private use during the life of the author.
No doubt, having experienced firsthand how the heart is "`deceitful above all things,
desperately wicked,`" and prone to backsliding,
he was unwilling to bring reproach upon the Truth by publishing his testimony
before knowing for certain that he had held out to the end.
He nevertheless lived nineteen years after the time of this writing,
and continued a faithful follower of Christ and a very useful member and
eventually minister of the Society of Friends until his decease in 1816.
A collection of his letters were gathered and published in the year 1819,
from which the following two samples are extracted.

[.asterism]
'''

[.letter-heading]
To a Religiously Disposed Young Man.

[.salutation]
Dear Friend,

The interest excited in my mind during the personal interactions
we have previously had relating to your eternal welfare,
now kindles with more than usual strength on my being
made acquainted with your present circumstances;
and under the feeling thereof, I in brotherly love take up my pen.

My heart is glad in the hope it feels of your standing
open to the manifestations of divine light,
and yielding full obedience to all its requirings in the
gradual unfoldings of your heavenly Father`'s good,
acceptable and perfect will concerning you.
This hope, I say, springs in me,
seeing you have already beheld the necessity of no
longer conforming to the present evil world,
both in its pomps and vanities, and its superstitious forms in spiritual things,
in order to experience that renewal of mind which must be witnessed before we
can clearly distinguish the voice of the good Shepherd from that of the stranger.
This much you have already seen,
and have formed the blessed resolution to desist
from further conference with flesh and blood,
by yielding obedience to the heavenly vision,
and daring for Christ`'s sake to become a fool in
the estimation of the wise of this world.
Now it remains for you to "`acknowledge Him in __all your ways,__`"^
footnote:[Proverbs 3:5]
as He draws you to Himself;
and be not discouraged if the way which is opened before you appears rough,
and you see but few traveling therein.
Confide in the promise that "`your sandals shall be iron and brass, and as your day is,
so shall your strength be.`"^
footnote:[Deuteronomy 33:25]

The present appears to me to be a time of most gracious
visitation to you--a day which the Lord has made,
in which He has passed by and looked upon you, and sweetly revealed Himself unto you.
Oh may you return love for love, while this day of power continues,
seeing it is only therein that a willingness is wrought in our souls to
make covenant with the Lord by such sacrifices as He may require.
To a heart fully yielded to this divine attraction,
nothing will appear too dear to part with,
nor will anything seem too painful to endure for the sake of Him
who has purchased us at the price of His own precious blood.
It is written, "`Love is as strong as death; many waters cannot quench it,
neither can floods drown it;`"^
footnote:[Song of Solomon 8:6-7]
but that death which has passed on all men will ever
be found a power that nothing but love can dethrone;
and from this power of death flow such waters as can and do quench
all man-made fires and creaturely zeal in every form.

Now then, dear friend,
is your time to "`arise and shake yourself from the dust of the
earth,`" and to "`loose yourself from the bands of your neck,`"^
footnote:[Isaiah 52:2]
and follow on to know the deliverer of Zion.
Now is your time to "`bind the sacrifice with cords to the horns of the altar,`"^
footnote:[Ps. 118:27]
and to aspire after a part and inheritance with those
who have both heard and obeyed the call,
"`Gather My saints together unto Me,
those that have made a covenant with Me by sacrifice.`"^
footnote:[Ps. 50:5]
Oh I do believe that if the called of the Lord in this day
did but unreservedly give up their hearts to Him,
and in simplicity rely upon _His living power within them,_
they would soon become wiser than their teachers,
and the light of His living and active Word would shine forth with a luster
that would eclipse much of what is now (by many) called gospel brightness.
But alas,
the cry of "`lo here,`" or "`lo there,`" is more listened
to than that inward voice which first called them.
And when their "`first love`"^
footnote:[Revelation 2:4]
(which was felt in its precious influences) begins to abate,
too often the mind settles into a systematic theology with various
observances and ordinances of man`'s invention--a rest far short
of that which is prepared for the children of God.

In view of these things,
it is a great comfort to me that you are disposed to make way in your
heart for the reception of gospel truth unmixed with creaturely conceptions,
and having seen that "`it is the Spirit that gives life;
the flesh profits nothing,`" you have formed the wise resolution to wait for,
and listen to "`Him that speaks from heaven,`"^
footnote:[Hebrews 12:25]
whose Word is with power, and is (as He Himself declared) "`Spirit and Life.`"^
footnote:[John 6:63]
This does indeed give me great satisfaction,
having long been convinced beyond a shadow of a doubt that nothing
short of this living power can dislodge Satan from our hearts,
or dispossess the world and the flesh of their hold on our affections and desires.
And having been thus taught in adorable mercy to
step a little forward in this new and living way,
and seeing Truth itself has declared there is no other way to the Father,
it is no marvel then that a concern rests upon me
to earnestly recommend it to all my fellow creatures,
especially such as are setting out on their heavenly journey.

Hold fast then, without wavering, what you have of this faith, I entreat you;
and in simplicity of heart yield yourself up to its workings.
Turn a deaf ear to the commonplace arguments in favor
of the current systems and outward modes of religion,
and rather avoid much discussion about them.
By a real and constant turning inward of your heart unto God,
you will find a renewal and increase of that strength which
will enable you so to let your light shine before men,
as to give undoubted evidence of its origin,
and thereby convince opposers more powerfully than by argument.
By thus accustoming yourself to continually seek access to your heavenly Father,
you will become more and more convinced of the emptiness
of worldly pursuits and creaturely enjoyments,
and a true relish for spiritual things will rise superior to all "`lying vanities.`"^
footnote:[Jonah 2:8]
By this also you will find your mind enlarged,
and the mysteries of the kingdom of God opened by Him who
keeps the "`key of David`" in His own possession.
Labor then, my dear friend,
to retire out of and turn from earthly objects (as much
as the duties of your outward calling will admit),
seeking always that bread which comes down from God out of heaven.
And do not let your allowed recreations be such as have
any tendency to deaden your aspirations after God;
keeping in mind the declaration of the apostle, "`He that says he abides in Him,
ought himself also to walk even as He walked.`"^
footnote:[1 John 2:6]

In taking up a resolution to appear in sober attire and to adopt simplicity of manners,
I trust you have followed, and not run before, your spiritual Guide.
Truly it is matter of surprise to me that spiritually-awakened persons
of all denominations do not see the necessity of bearing a faithful testimony
against the manifest pride and vanity in these things.
If any then think it strange that you should step out of the common path in this respect,
they may be answered in the language of David: "`Is there not a cause?`"^
footnote:[1 Samuel 17:29]

Though I have said much,
there is yet one matter concerning which I do not feel quite easy to be silent,
and that is the necessity of "`counting the cost`"^
footnote:[Luke 14:28]--that cost which all true disciples of a crucified
Lord must submit to in order to attain the pearl of great price.
Indeed, it is necessary to fully understanding the apostle`'s declaration that "`we must,
through much tribulation, enter into the kingdom of God.`"^
footnote:[Acts 14:22]
Setting out with this in view,
you will be in some degree armed against the assaults and temptations of our cruel foe.
For when the ability to sense divine favor is, in wisdom,
withdrawn from those who have begun their journey in the light,
and when the darkness that remains then becomes more manifest,
the enemy frequently tempts the soul with the suggestion that all
that it formerly enjoyed and believed in was a delusive imagination.
And at these times, when the strength of evil is deeply felt,
there is a disposition in the humble to listen too much to the voice of the enemy,
and to allow the taunting question, "`Where is your God now?`"--rather than,
in naked faith, to embrace the encouraging language of the prophet,
"`Who among you walks in darkness and has no light?
Let him trust in the name of the Lord and lean upon his God.`"^
footnote:[Isaiah 50:10]
Nevertheless, I firmly believe that the truly devoted soul,
who in sincerity has set his heart to follow the Lamb wheresoever He goes,
will be enabled to abide this hour and power of darkness,
and that love to their suffering Savior will produce a willingness to go with
Him over the Brook Kidron and take their allotted portion of that cup which,
in drinking, caused Him to sweat great drops of blood.
And so being strengthened by this almighty Redeemer and
Preserver of men in whatever trials He may see fit to dispense,
may this language be uttered in humble resignation, "`Not my will, but yours be done.`"

This last comment might appear to some to be ill-timed and discouraging; to me, however,
it seems safe.
We must not think ourselves more wise than the great and compassionate
Teacher who was well acquainted with the timidity of His little ones,
and who, while they were yet in a state of infancy,
told them plainly that all pretensions to discipleship were vain unless
there was a willingness to deny self and bear the daily cross.
I have never felt unity with a certain form of fleshly wisdom which,
in endeavoring to enlist soldiers under Christ`'s banner,
endeavors to allure with temporary gratification while keeping
out of view the hardness which must be endured.
And now, my dear friend, I conclude, commending you to God and the Word of His grace,
as being that which is able to build you up.
May you be favored to increase in the strength of the Lord and in the power of His might,
so as to stand in the evil day, and having done all, to stand.

[.signed-section-closing]
I affectionately bid you farewell,

[.signed-section-signature]
William Lewis

[.asterism]
'''

[.letter-heading]
To a Young Member of the Church of England

[.salutation]
Beloved friend,

At an early period of your life,
my pen was used to convey to you something of that love which encompasses
all God`'s intelligent creation in its wide embrace,
and which (being pure in nature and origin) seeks glory and virtue for all;
directing them to such holiness of heart and life as capacitates
them for union and communion with the Fountain of all good.

Neither lapse of time, nor lack of personal interaction,
has erased my first impressions concerning you.
I still remember the breathings of your spirit to the God of your life at a time
when you were led to consider the shortness and uncertainty of time,
and the awful condition of those who, on their deathbeds, feel their lack of Christ.
Then a lively concern arose in you to improve your talent,
and to devote your time to the blessed purpose of seeking, by prayer in your closet,
communion with the Beloved of souls.
I well remember how, when looking unto Jesus,
you were enabled to see the necessity of a more frequent
and earnest turning to Him in this manner,
and a foregoing of those foolish amusements in which
people spend most of their precious hours.
Thus yielding to the sweet attraction of everlasting love,
you were carried as in the bosom of Israel`'s tender shepherd;
and tasting His kindness yourself,
you did manifest to others that "`out of the mouths of babes and sucklings He
(still) ordains praise,`" testifying to all present that "`We must consider this
world as given to us merely to prepare us for the next.`"

All this, I say, dear friend, is now remembered and fresh in my mind.
Bear with me then, if under this impression,
I suggest to you the danger we are all in of departing from the fervent and chaste
"`love of our betrothal,`" unless we maintain a most determined purpose of heart,
strengthened by daily watching and earnest prayer
to Him who alone is able to keep us from falling.
Danger is on every side,
and continues through the several stages of our christian journey and warfare,
from the combined forces of this world`'s allurements
and the desires of our fallen nature.

If then,
after taking steps in the "`way to Zion,`" and attaining some knowledge (by living
experience) of both the Lord`'s goodness and our own weakness and depravity;
if still, through the treachery of our own spirits,
we are all in continual danger of falling away,
how much more may the crafty tempter of souls draw
aside the youthful and inexperienced mind?
For young persons are peculiarly beset with desires within and temptations without,
and if there is not a constant endeavor to flee from both,^
footnote:[2 Timothy 2:22; 1 Peter 2:11]
these will so wage war against the soul as to gradually bring down all its strength,
and rob and spoil it of its peace with God.
It is in this stage of your life that I now address you in the love of my spirit;
and knowing that there are also many dangers that are unique to your present situation,
I cannot help but feel a strong concern on your account,
lest the first green buddings of the plant of righteousness in
your soul should inhale the infectious breath of the world`'s spirit,
and so be nipped before the blossom fully opens.
Or, to change the metaphor, that by forsaking the pure light of Jesus Christ,
"`your silver should become dross,`" and "`your wine be mixed with water.`"^
footnote:[Isaiah 1:22]
Nothing, my friend,
can preserve you from this but a single eye to the glory of God in all your thoughts,
desires and purposes, and an entire dependance upon the quickening,
cleansing and illuminating grace which is in Christ Jesus.
Without this grace,
we can do nothing that can kindle or keep alive one spark of heavenly life,
or wash the stain of sin from our immortal souls.
And without this single eye, the heart is ever divided and unstable,
our faithfulness is as the morning cloud that goes away,
and we will have no capacity to receive that shining
which makes "`the whole body full of light.`"^
footnote:[Matthew 6:22-23]

Oh this power of God that truly makes Jesus Lord in us, and "`wisdom, righteousness,
sanctification, and redemption!`"^
footnote:[1 Corinthians 1:30]
What an error to expect help from anything short of this!
For seeing that the need we have of a Savior lies in our deep fall
from the holy image of God in which He first created man,
into an earthly and sensual life;
seeing also that nothing can possibly effect a real change in our state
but that same power which first gave life to all intelligent spirits;
it is therefore vain and ineffectual to expect the work of redemption
from any name (or power) under heaven but that of Christ--the living
Word by which all things were at first created.
Thus, in all our seeking of God, let us seek Him as a life-giving Spirit from heaven,
who alone can raise our inner man up to a heavenly place or state; and who,
having so raised it, can keep from falling again.
Let us seek him as a seed of the divine nature,
a kingdom or manifestation of God within us, "`that we might grope for Him`"^
footnote:[Acts 17:27]
and indeed find Him to be "`Immanuel, God with us.`"^
footnote:[Matthew 1:23]
I trust I am not speaking to you altogether in an unknown tongue;
but that from your attentive perusal of the holy Scriptures,
with an understanding measurably enlightened,
and a heart opened to receive the truth as it is in Jesus,
you are convinced that what was lost in the first Adam,
and that which the Lord from heaven, the life-giving Spirit, revives in man,
is a state of life, even a divine life,
that is according to the image of Him who at the first created him therein.^
footnote:[Colossians 3:10]

When it is at last known and felt,
that __life__--the life of God--is what we are alienated from and dead to,
how many other things dwindle into insignificance!
How weak and vain appears the least reliance upon opinions, creeds, modes of worship,
and particularly upon man`'s natural abilities, however highly cultivated!
Under this conviction, all is accounted less than nothing and vanity,
apart from the manifestation of that life which is the light of men,
which quickens and comforts with the sensible evidence
of its indeed being in us and we in it,
joined to, and one spirit with our redeeming Lord, "`hidden with Christ in God.`"^
footnote:[Colossians 3:3]

Now, what is it that prepares the heart for the full reception of such doctrine as this?
Nothing less than a hunger and thirst after righteousness;
a sincere and ardent longing after that purity of heart in which we can now enjoy,
and ultimately see our God.
For in seeking and striving after this state,
the soul is soon painfully aware of the insufficiency,
not only of outward observances or the help of man,
but also of its own efforts (however sincere and earnest) to effect a real change,
or to lay the axe to the deep root of a fallen nature.
With this new discernment and sensibility,
the earnest seeker is soon driven from all carnal dependence on this or that thing,
and a cry is raised which reaches the ear of Omnipotence.
Out of the depths of a contrite spirit,
the eye of the soul is then directed unto Him who dwells in the heavens,
even to Him who remains the High Priest of His church,
and who alone communicates the one thing needful, that is,
"`the _power_ of an endless life.`"^
footnote:[Hebrews 7:16]
Therefore, the real and constant longing of the soul after heavenly purity,
becomes its capacity for true illumination, and its certain way thereto.
And when this is accompanied with true resignation and submission
of the creaturely will to that of the Creator,
in which both become "`one spirit,`" it has the promise
of true discernment from Christ Himself,
who said, "`If _anyone wills to do His will,_ he shall know concerning the doctrine,`"^
footnote:[John 7:17] etc.

Find here, my dear friend, your school and your true exercise therein,
if you desire to advance in real christian knowledge and experience.
Ponder deeply these words of your Lord,
and yield your judgment to all the consequences that necessarily flow from them.
Oh that there were more students in this inward christian academy!--then
there would be a real benefit in the church from the labors of
workmen who themselves had been taught by God.
Such ministers,
who first knowing in their own experience that His kingdom (or
divine life restored to the soul) is not in word but in power,
would express a uniform concern that the faith of
their hearers stand solely in this power.
And on the other hand, seeing clearly how a laborious,
brain-studied and scholastic knowledge,
clothed with the most attractive display of rhetoric and oratory,
can go no further than a ministration of the letter,
they would willingly and naturally leave such performances to the wise of this world.
But where,
or in what church shall we find such pastors who are willing to
forego all the honor that is lavished upon the gifted and eloquent?
Were such simple ones again to arise,
resting all hope of helping their hearers on the power of Christ,
it is to be feared such preachers would not have many hearers.

Perhaps you are a little surprised at my speaking
in this way of the present state of the church.
I am aware that a different view of things is generally accepted,
but that does not shake my judgment in the least.
I desire not to exceed appropriate limits on this subject,
so I will just touch upon one or two other marks
of degeneracy that I feel are too obvious to be overlooked.
Can there be a stronger delusion in judgment than to suppose that the seeking of riches,
honor and the enjoyment of pleasure in this present world is compatible
with the example of our holy Lord and Savior Jesus Christ?
Is it not apparent, rather,
that the first great deceiver and foe of mankind
has spread his delusive influence in the human mind,
seeing that the bulk of professing christians believe
they have taken Christ for their Lawgiver and pattern,
even while they are not only allowing but seeking ease and elegance in their dwellings,
worldly honors and distinctions, excess of bread,
and in some instances an "`abundance of idleness`"^
footnote:[Ezekiel 16:49]
in their daily lives?
Though we have eyes,
are we yet so blind as not to see the open and glaring contradiction
exhibited between the allowed practices and customs of the day,
and the plain doctrines and example of our world-renouncing Lord?
Surely the enemies of the Lord Jesus, the deists and infidels of every class,
are more quick-sighted than this,
and are therefore amply furnished for their sarcastic criticism and derision.
"`These so-called pilgrims and strangers in the earth,`" they say,
"`seem to have well-reconciled themselves to this foreign land,
though they claim to be so far from their native country and Father`'s house.
Indeed they seem to sit down here like us,
each under their own vine and under his own fig tree.
And though they say we are to be forever separated at the
end of the journey--they raised up to everlasting glory,
and we consigned to shame and everlasting contempt--yet
we really appear to be traveling in the same direction,
walking in great harmony as friends.`"

Oh how long shall the enemies of the cross of Christ have cause thus to triumph?
How long shall they speak proud and contemptuous things against the Lord,
because of the occasion given by those who on the one hand profess
adherence to doctrines which demand the crucifixion of the flesh,
and on the other hand are seen making full provision for the gratification of its desires!
My eye, when fixed on these things, affects my heart, and as I watch,
sitting alone as a sparrow on the house-top,
my inward language often accords with that of the Prophet,
"`The faithful man has perished from the earth, and there is no one upright among men,`"^
footnote:[Micah 7:2]
etc.

What has been already mentioned relates to practice; but oh,
what shall be said with respect to doctrine,
even some of that doctrine which is preached and enforced by those
who assume the title of evangelical teachers and gospel ministers?
To teach, for example, the appropriateness of using the devouring sword,
spreading desolation, destruction,
and every kind of horror among the Lord`'s intelligent creatures through war,
and suggesting the compatibility of this with the spirit of the meek, passive, loving,
suffering Lamb of God, and with His precepts and commands.
Or to charge the God of love with partiality,
by declaring that His offer of redemption in Christ
Jesus is limited--reaching only to a chosen few;
while the rest, myriads upon myriads, in every generation,
born heirs of Adam`'s pollution and misery, are left to perish eternally,
never having been designated in the secret counsel of God to be included in His covenant,
nor given that redeeming power which alone can deliver from eternal death.

These are some of the marks that the present is, I believe,
a dark day--a day in which the children of the light
should indeed hold fast to the Word of truth,
having no fellowship with such shocking errors.
It seems to me very desirable,
that even beginners in religion should have a clear
view of the time in which their lot has been cast.
For indeed, this same sort of blindness so hardened the hearts of the teachers, rulers,
and professors of Judaism,
as to render them insensible to the combined force of miraculous power, heavenly wisdom,
and divine love,
united and continually manifested in Jesus Christ their long promised Messiah.
Apprehending their orthodoxy to be enlightened and their practices pure,
they fled from His convicting light in their own conscience.
And though at times they were sensible that no man ever spoke as He did,
yet all was rejected, and their Redeemer`'s doctrines and miracles were despised,
because the chief pharisees and rulers "`believed Him not.`"
That this old leaven of the religious leaders is too prevalent in the present day, must,
I think, be obvious to all seeing eyes.
Resting upon the current opinions of orthodoxy of whatsoever community we may be members,
is as dangerous now as it was formerly.
I therefore cannot help but think that a clear view of the "`signs
of our times`" is needful for all who truly desire to come out
of spiritual Babylon and make straight steps towards mount Zion.

The latter part of this communication was not in
my view when I first sat down to write you.
Were I to reason upon it,
my faith might possibly waver a little as to its being food
appropriate for your present state and growth.
But I retain a hope that it may, at least, prove as "`bread cast upon the waters,
that will be found after many days;`"^
footnote:[Ecclesiastes 11:1]
and in that hope I leave it to your serious consideration.
A weakened and still weakening tabernacle makes me admit of the possibility
of this being the last token of my christian love to you,
my dear friend.
I have given freedom to my pen,
and kept back nothing that I believed might now or hereafter prove profitable to you.
Allow then, this word of exhortation,
and may the Father of lights bless it to your understanding and your heart also!
May He fit and prepare you for the reception of that anointing
which renders teaching through instruments needless,
even the living Truth itself, unmixed and infallible!
To Him then, and the Word of His grace,
as that alone which can "`build you up,`" I must now commend you.
Be faithful, I entreat you, to your God!
His call to holiness you have heard;
His drawings of tender love you have felt and rejoiced in.
May He never leave you nor forsake you, until He has done all that to you and for you,
which the first gentle whispers of His Spirit spoke to you of,
and which you then did so earnestly desire.

[.signed-section-signature]
William Lewis
